# Generated by Django 4.0 on 2021-12-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
