# Generated by Django 4.0 on 2021-12-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
